experiment:
  name: debug
  save_checkpoint_every: 2000
  n_epochs: 20000000


runner:
  ccraft:
    warmup_steps: 100
    n_opt_steps: 1
    increase_roll_every: 5000
    roll_max: 20
    push_eps: 2e-3
    initial_ts: 3.333333333333333e-1
    regular_ts: 3.333333333333333e-2
    use_restpos_for_strain_tensor: True
    opposite_edges: False
    grad_clip: 1.
    random_pin_nobody: False
    n_random_pin_nobody: 2
    nocollect_after: 2
    no_world_edges_every: 2
    fake_icontour: False
    optimizer:
      lr: 2e-3
      decay_steps: 50_000
      decay_rate: 5e-1
    material:
      lame_mu_min: 15909
      lame_mu_max: 63636
      lame_lambda_min: 3535.414406069427
      lame_lambda_max: 93333.73508005822
      bending_coeff_min: 6.370782056371576e-08
      bending_coeff_max: 0.0013139737991266374
      density_min: 4.34e-2
      density_max: 7e-1
    safecheck:
      max_riz_size: 30
      n_rest2pos_steps: 10
      max_impulse_norm: 5e-2
      max_ncoll: 2000
      riz_epsilon: 0

dataloader:
  num_workers: 0
  batch_size: 1
  pyg_data: True
  dataset:
    postcvpr:
      data_root: 'vto_dataset/smpl_parameters'
      body_model_root: 'body_models'
      model_type: 'smpl'
      gender: 'female'
      garment_dict_file: 'garments_dict.pkl'
      obstacle_dict_file: 'smpl_aux.pkl'
      split_path: 'datasplits/train.csv'
      pinned_verts: True
      random_betas: False
      n_coarse_levels: 3
      separate_arms: True
      wholeseq: True
      noise_scale: 0

criterions:
  postcvpr.mataug.stretching_energy:
  postcvpr.inertia:
  postcvpr.gravitational_energy:
    z_axis: 1
  postcvpr.collision_penalty:
    weight_start: 5e+3
    weight_max: 5e+5
    eps: 2e-3
    start_rampup_iteration: 50000
    n_rampup_iterations: 100000
  postcvpr.mataug.bending_energy:
  postcvpr.friction_energy:
    mu: 0.5
    friction_radius: 3e-3

model:
  ccraft:
    core_model: 'ccraft'
    architecture: "f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3|f,c3"
    collision_radius: 3e-2
    body_collision_radius: 3e-2
    n_coarse_levels: 4

device: 'cuda:0'